spring:
  activemq:
    broker-url: tcp://${ACTIVE_MQ_HOST}:${ACTIVE_MQ_PORT}
    user: ${ACTIVE_MQ_USER}
    password: ${ACTIVE_MQ_PASSWORD}
jms:
  request-queue: dev.cbr.request
  response-queue: dev.cbr.response
web-service:
  endpoint: http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx

